export const video = {
    VIDEO_LOADING: "VIDEO_LOADING",
    VIDEO_GET_LIST_REQUEST: "VIDEO_GET_LIST",
    VIDEO_GET_LIST_SUCCESS: "VIDEO_GET_LIST_SUCCESS",
    VIDEO_GET_LIST_FAILURE: "VIDEO_GET_LIST_FAILURE"
  };